initialValue: &initialValue
  SMTP_HOST: smtp.exmail.qq.com

collecting_statistics: &collecting_statistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - wenci.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
  SQL_CONFIG: daily_statistics_collection

return_visit_statistics: &return_visit_statistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - wenci.zhang@worldfarm.com
  SQL_CONFIG: daily_return_visit_list

acquired_commodity_statistics: &acquired_commodity_statistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
      - shicao.he@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
  SQL_CONFIG: acquired_commodity_statistics


punch_card: &punch_card
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
      - shicao.he@worldfarm.com
      - tong.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
      - qinhu.peng@worldfarm.com
  SQL_CONFIG: ClockInAndOutStatistics

AssetReleaseStatistics: &AssetReleaseStatistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - wenci.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
      - haodong.xian@worldfarm.com
  SQL_CONFIG: asset_issuance_statistics

AssetReleasefafang: &AssetReleasefafang
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
      - qiuming.yang@worldfarm.com
      - haodong.xian@worldfarm.com
  SQL_CONFIG: Asset_recovery_statistics

statisticsziyingfengcheng: &statisticsziyingfengcheng
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - jiangwei.huang@worldfarm.com
      - yuping.dai@worldfarm.com
  SQL_CONFIG: statistics_ziying_fengchang

collectionFriendSwarmInfoStististics: &collectionFriendSwarmInfoStististics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - jiangwei.huang@worldfarm.com
  SQL_CONFIG: collection_friend_swarm_info_stististics

invoiceandreceipt: &invoiceandreceipt
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - yilin.zhou@worldfarm.com
      - wei.zhang@worldfarm.com
  SQL_CONFIG: mp_wms_invoice_and_receipt