initialValue: &initialValue
  SMTP_HOST: smtp.exmail.qq.com

collecting_statistics: &collecting_statistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  SQL_CONFIG: daily_statistics_collection
