initialValue: &initialValue
    smtpHost: smtp.exmail.qq.com

QA:
    <<: *initialValue
    receiver: [yong.guo@worldfarm.com,wei.zhang@worldfarm.com]


PROD:
    <<: *initialValue
    receiver: [yong.guo@worldfarm.com,wei.zhang@worldfarm.com]
