initialValue: &initialValue
  smtpHost: smtp.exmail.qq.com

collecting_statistics: &collecting_statistics
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - xinran.liang@worldfarm.com
      - wenci.zhang@worldfarm.com
  sql_file:
    - flowerSQL.sql

return_visit_statistics: &return_visit_statistics
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - wenci.zhang@worldfarm.com
  sql_file:
    - return_visit_statisticsSQL.sql
20:
  <<: *collecting_statistics

23:
  <<: *collecting_statistics

22:
  <<: *return_visit_statistics