initialValue: &initialValue
  smtpHost: smtp.exmail.qq.com

collecting_statistics: &collecting_statistics
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - xinran.liang@worldfarm.com
      - wenci.zhang@worldfarm.com
  sql_file:
    - flowerSQL.sql

return_visit_statistics: &return_visit_statistics
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - wenci.zhang@worldfarm.com
  sql_file:
    - return_visit_statisticsSQL.sql
20:
  <<: *collecting_statistics

23:
  <<: *collecting_statistics

22:
  <<: *return_visit_statistics


acquired_commodity_statistics: &acquired_commodity_statistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
      - shicao.he@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
  sql_file:
    - acquired_commodity_statistics.sql


punch_card: &punch_card
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
      - shicao.he@worldfarm.com
      - tong.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
      - qinhu.peng@worldfarm.com
  sql_file:
    - punch_card.sql

AssetReleaseStatistics: &AssetReleaseStatistics
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - wenci.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
  sql_file:
    - Asset_release_statistics.sql

AssetReleaseStatisticsAll: &AssetReleaseStatisticsAll
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
  sql_file:
    - Asset_release_statistics_all.sql
AssetReleasefafang: &AssetReleasefafang
  QA:
    <<: *initialValue
    receiver:
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - tong.zhang@worldfarm.com
      - wei.zhang@worldfarm.com
      - shichao.he@worldfarm.com
      - wenci.zhang@worldfarm.com
      - jianbin.wang@worldfarm.com
      - fo.he@worldfarm.com
  sql_file:
    - asset_release_fafang.sql