env: QA


initialValue: &initialValue
    smtpHost: smtp.exmail.qq.com
    port: 3306
    sender: miaoshu@worldfarm.com
    host: 47.74.225.79
    username: qa

QA:
    <<: *initialValue
    receiver: [yong.guo@worldfarm.com,wei.zhang@worldfarm.com]


PROD:
    <<: *initialValue
    receiver: [yong.guo@worldfarm.com,wei.zhang@worldfarm.com]
