initialValue: &initialValue
  smtpHost: smtp.exmail.qq.com

collecting_statistics: &collecting_statistics
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - xiaofan.zhang@worldfarm.com
      - xinran.liang@worldfarm.com
  execute_time: 20
  sql_file:
    - flowerSQL.sql

return_visit_statistics: &return_visit_statistics
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - xiaofan.zhang@worldfarm.com
      - xinran.liang@worldfarm.com
  execute_time: 22
  sql_file:
    - flowerSQL.sql
20:
  <<: *collecting_statistics

22:
  <<: *return_visit_statistics