initialValue: &initialValue
  smtpHost: smtp.exmail.qq.com
20:
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - xiaofan.zhang@worldfarm.com
      - xinran.liang@worldfarm.com
  sql_file:
    - flowerSQL.sql
  execute_time: 20
22:
  QA:
    <<: *initialValue
    receiver:
      - yong.guo@worldfarm.com
      - wei.zhang@worldfarm.com
  PROD:
    <<: *initialValue
    receiver:
      - xiaofan.zhang@worldfarm.com
      - xinran.liang@worldfarm.com
  sql_file:
    - flowerSQL.sql
  execute_time: 22