EMAIL_TITLE: "资产发放统计"
CONF_VERSION: 1
BUSUNESS:
  - TABLE_TITLE: "每日资产发放统计"
    SUB_BUSUNESS:
      - MERGE: True
        MERGE_KEY: '操作人'
        BUSUNESS_NAME: '每日资产发放统计'
        BUSUNESS_SQL_FILE: creator_name.sql
        BUSUNESS_VICE_MERGE: True
        BUSUNESS_VICE_MERGE_KEY: '操作人'
        DB_NAME: "flower"
        REPLACE_KEY:
          - REPLACE_VALUE: "操作人list"
            CONDITION_VALUE: "操作人"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '每日资产发放统计-蜂友蜂场数据查询'
            DATA_SQL_FILE: daily_release_asset_bee_friend_data.sql
      - MERGE: True
        MERGE_KEY: '蜂场id'
        BUSUNESS_NAME: '每日资产发放蜂场统计'
        BUSUNESS_SQL_FILE: asset_release_apiary_info.sql
        DB_NAME: "flower"
        REPLACE_KEY:
          - REPLACE_VALUE: "swarmid"
            CONDITION_VALUE: "蜂场id"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '每日资产发放统计-蜂友蜂场数据查询'
            DATA_SQL_FILE: daily_release_asset_bee_friend_data.sql
  - TABLE_TITLE: "每日资产发放统计"
    SUB_BUSUNESS:
      - MERGE: True
        MERGE_KEY: '操作人'
        BUSUNESS_NAME: '历史资产发放统计统计'
        BUSUNESS_SQL_FILE: creator_name.sql
        BUSUNESS_VICE_MERGE: True
        BUSUNESS_VICE_MERGE_KEY: '操作人'
        DB_NAME: "flower"
        REPLACE_KEY:
          - REPLACE_VALUE: "操作人list"
            CONDITION_VALUE: "操作人"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '历史资产发放统计-蜂友蜂场数据查询'
            DATA_SQL_FILE: historical_asset_issuance_statistics.sql
      - MERGE: True
        MERGE_KEY: '蜂场id'
        BUSUNESS_NAME: '历史资产发放蜂场统计'
        BUSUNESS_SQL_FILE: asset_release_apiary_info.sql
        DB_NAME: "flower"
        REPLACE_KEY:
          - REPLACE_VALUE: "swarmid"
            CONDITION_VALUE: "蜂场id"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '历史资产发放统计-蜂友蜂场数据查询'
            DATA_SQL_FILE: historical_asset_issuance_statistics.sql