EMAIL_TITLE: "每日采集蜂友统计"
CONF_VERSION: 2
BUSUNESS:
  - TABLE_TITLE: "每日采集蜂友蜂场统计"
    TABLE_FIELD_SORTING: ['采集人', '采集日期', '采集人电话', '今日采集蜂友数', '今日采集蜂场数', '今日采蜂友场登录数',
                          '今日采集蜂场登录数', '开始采集时间', '结束采集时间', '推广蜂友天气设定人数', '推广蜂友发布蜂友互助的数量_人',
                          '推广蜂友发布蜂友互助的数量_条数', '1月20日后采集蜂友数', '1月20日后采集蜂场数']
    FIELD_DATA_SORTING: '今日采集蜂场数'
    SUB_BUSUNESS:
      - MERGE: True
        MERGE_KEY: '采集人'
        BUSUNESS_NAME: '每日采集蜂友统计'
        BUSUNESS_SQL_FILE: collection_friend_swarm_info_stististics.sql
        DB_NAME: "flower"
        BUSUNESS_MAPPING:
          - MAPPING_KEY: None
            MAPPING_FILE: None
        REPLACE_KEY:
          - REPLACE_VALUE: "login_userid"
            CONDITION_VALUE: "user_id"
        VICE_DATA:
          - DATA_DB_NAME: "base"
            DATA_NAME: '每日采集蜂友统计-每日登陆数据'
            DATA_SQL_FILE: day_login_data.sql