EMAIL_TITLE: "追花族采集统计"
CONF_VERSION: 1
BUSUNESS:
  - TABLE_TITLE: "每日采集统计"
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: None
        BUSUNESS_NAME: '每日采集统计'
        BUSUNESS_SQL_FILE: daily_statistics_collection.sql
        DB_NAME: "flower"
  - TABLE_TITLE: "累计采集统计"
    SUB_BUSUNESS:
      - MERGE: True
        MERGE_KEY: None
        BUSUNESS_NAME: '累计采集统计'
        BUSUNESS_SQL_FILE: cumulative_statistics_collection.sql
        DB_NAME: "flower"
      - MERGE: True
        MERGE_KEY: None
        BUSUNESS_NAME: '蜂友统计'
        BUSUNESS_SQL_FILE: bee_friends_collection.sql
        DB_NAME: "base"