EMAIL_TITLE: "每日回访名单"
CONF_VERSION: 1
BUSUNESS:
  - TABLE_TITLE: "今日登录的蜂友"
    TABLE_FIELD_SORTING:
    FIELD_DATA_SORTING:
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: None
        BUSUNESS_NAME: '今日登录的蜂友汇总'
        BUSUNESS_SQL_FILE: daily_login_statistics.sql
        DB_NAME: "flower"
  - TABLE_TITLE: "今日设置天气的蜂友"
    SUB_BUSUNESS:
      - MERGE: False
        BUSUNESS_NAME: '今日设置天气的蜂友汇总'
        MERGE_KEY: None
        BUSUNESS_SQL_FILE: daily_weather_statistics.sql
        DB_NAME: "flower"
  - TABLE_TITLE: "今日调车的蜂友"
    SUB_BUSUNESS:
      - MERGE: False
        BUSUNESS_NAME: '今日调车的蜂友汇总'
        MERGE_KEY: None
        BUSUNESS_SQL_FILE: daily_shunt_statistics.sql
        DB_NAME: "flower"