EMAIL_TITLE: "WMS数据汇总"
CONF_VERSION: 1
BUSUNESS:
  - TABLE_TITLE: "入库通知单"
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: 'user_id'
        BUSUNESS_NAME: '入库通知单用户信息'
        BUSUNESS_SQL_FILE: query_username.sql
        BUSUNESS_VICE_MERGE: True
        BUSUNESS_VICE_MERGE_KEY: 'user_id'
        DB_NAME: "flower"
        BUSUNESS_MAPPING:
          - MAPPING_KEY: ['来源系统','单据类型']
            MAPPING_FILE: mp_wms_document_type
        REPLACE_KEY:
          - REPLACE_VALUE: "userid"
            CONDITION_VALUE: "user_id"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '入库通知单-入库通知单单据信息'
            DATA_SQL_FILE: warehousing_notice.sql
  - TABLE_TITLE: "入库单"
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: 'user_id'
        BUSUNESS_NAME: '入库单'
        BUSUNESS_SQL_FILE: query_username.sql
        BUSUNESS_VICE_MERGE: True
        BUSUNESS_VICE_MERGE_KEY: 'user_id'
        DB_NAME: "flower"
        BUSUNESS_MAPPING:
          - MAPPING_KEY: ['来源系统','单据类型']
            MAPPING_FILE: mp_wms_document_type
        REPLACE_KEY:
          - REPLACE_VALUE: "userid"
            CONDITION_VALUE: "user_id"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '入库单-入库单'
            DATA_SQL_FILE: warehousing_list.sql
  - TABLE_TITLE: "出库通知单"
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: 'user_id'
        BUSUNESS_NAME: '出库通知单'
        BUSUNESS_SQL_FILE: query_username.sql
        BUSUNESS_VICE_MERGE: True
        BUSUNESS_VICE_MERGE_KEY: 'user_id'
        DB_NAME: "flower"
        BUSUNESS_MAPPING:
          - MAPPING_KEY: ['来源系统','单据类型']
            MAPPING_FILE: mp_wms_document_type
        REPLACE_KEY:
          - REPLACE_VALUE: "userid"
            CONDITION_VALUE: "user_id"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '出库通知单-出库通知单'
            DATA_SQL_FILE: outbound_notice.sql
  - TABLE_TITLE: "出库单"
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: 'user_id'
        BUSUNESS_NAME: '出库单'
        BUSUNESS_SQL_FILE: query_username.sql
        BUSUNESS_VICE_MERGE: True
        BUSUNESS_VICE_MERGE_KEY: 'user_id'
        DB_NAME: "flower"
        BUSUNESS_MAPPING:
          - MAPPING_KEY: ['来源系统','单据类型']
            MAPPING_FILE: mp_wms_document_type
        REPLACE_KEY:
          - REPLACE_VALUE: "userid"
            CONDITION_VALUE: "user_id"
        VICE_DATA:
          - DATA_DB_NAME: "mp"
            DATA_NAME: '出库单-出库单'
            DATA_SQL_FILE: outbound_order.sql