EMAIL_TITLE: "自营蜂场统计"
CONF_VERSION: 1
BUSUNESS:
  - TABLE_TITLE: "自营蜂场统计"
    SUB_BUSUNESS:
      - MERGE: False
        MERGE_KEY: None
        BUSUNESS_NAME: '自营蜂场统计汇总'
        BUSUNESS_SQL_FILE: statistics_ziying_fengchang.sql
        DB_NAME: "flower"